modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
mixinConfigs="rtfs.mixins.json"

[[mods]]
modId="rtfs"
displayName="ReTerraForged"
version="${version}"
authors="rayman"
credits="rayman"
logoFile="logo.png"
displayURL="https://github.com/rayman/rtfs/"
issueTrackerURL="https://github.com/rayman/rtfs/issues"
description="A continuation of https://github.com/TerraForged/TerraForged"

[[dependencies.rtfs]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.rtfs]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.20.1,)"
	ordering = "NONE"
	side = "BOTH"
